name: Latest blog posts
on:
  schedule:
    - cron: '15 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://amirhjalali.com/feed.xml"
          max_post_count: 5
          template: "- **[$title]($url)**"
          commit_message: "Update blog posts in README"
          committer_username: "blog-post-bot"
          committer_email: "actions@github.com"
